name: USPMUN-Jekyll
title: USPMUN
description: Simulação de organismos internacionais da Universidade de São Paulo
url: https://uspmun.com.br/
logo: /apple-touch-icon.png
lang: pt_BR

collections:
  authors:
    output: true
  comites:
    output: true
  comites-2018:
    output: false

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "comites"
    values:
      layout: "comite"
  - scope:
      path: ""
    values:
      layout: "title"
