name: USPMUN-Jekyll
title: USPMUN
description: Simulação de organismos internacionais da Universidade de São Paulo
url: https://uspmun.com.br/
logo: https://uspmun.com.br/apple-touch-icon.png
lang: pt_BR

collections:
  authors:
    output: true
  comites:
    output: false
  comites-2018:
    output: false

defaults:
  - scope:
      path: ""
      type: "comites"
    values:
      layout: "comite"
  - scope:
      path: ""
    values:
      layout: "title"
  # - scope:
  #     path: ""
  #     type: "authors"
  #   values:
  #     layout: "author"
  # - scope:
  #     path: ""
  #     type: "posts"
  #   values:
  #     layout: "post"
